name: Maven CI with Nexus IQ

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 17
        distribution: 'zulu'
        # Optional, but required if ScanCentral Controller requires client authentication
    - name: Setting FQDN address
      run: |
              export RUNNER_ALLOW_RUNASROOT="1"
              export AGENT_ALLOW_RUNASROOT="1"
              sudo echo "75.101.132.221 fortify.cyberxdemo.com" | sudo tee -a /etc/hosts
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        serverUrl: https://fortify.cyberxdemo.com:14443/
        username: koeIFKXW
        password: ${{ secrets.SONATYPE_PWD }}
        applicationId: sample-maven
        stage: Build
        target: ./target/
