name: Maven CI with Nexus IQ

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 17
        distribution: 'zulu'
        # Optional, but required if ScanCentral Controller requires client authentication
    - name: Setting FQDN address
      run: |
              export RUNNER_ALLOW_RUNASROOT="1"
              export AGENT_ALLOW_RUNASROOT="1"
              sudo echo "75.101.132.221 fortify.cyberxdemo.com" | sudo tee -a /etc/hosts
              cat /etc/hosts
              wget https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/scanner/nexus-iq-cli-1.165.0-01+664-unix.zip
              unzip nexus-iq-cli-1.165.0-01+664-unix.zip
              rm nexus-iq-cli-1.165.0-01+664-unix.zip
              chmod +x nexus-iq-cli
              ls -l
              wget https://repository.emsign.com/certs/emSignRootCAG1.crt
              wget https://repository.emsign.com/certs/emSignSSLCAG1.crt
              wget https://fortify.cyberxdemo.com:8443/ssc/downloads/fortify.cyberxdemo.com.crt
              sudo /opt/hostedtoolcache/jdk/17.0.8/x64/bin/keytool -keystore /opt/hostedtoolcache/jdk/17.0.8/x64/lib/security/cacerts -importcert -alias myroot -file emSignRootCAG1.crt -storepass changeit -noprompt
              sudo /opt/hostedtoolcache/jdk/17.0.8/x64/bin/keytool -keystore /opt/hostedtoolcache/jdk/17.0.8/x64/lib/security/cacerts -importcert -alias myroot1 -file emSignSSLCAG1.crt -storepass changeit -noprompt
              sudo /opt/hostedtoolcache/jdk/17.0.8/x64/bin/keytool -keystore /opt/hostedtoolcache/jdk/17.0.8/x64/lib/security/cacerts -importcert -alias myroot2 -file fortify.cyberxdemo.com.crt -storepass changeit -noprompt
             
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Run Sonatype Scan
      run: |
            zip ./sample-application.zip -r -v *
            ./nexus-iq-cli -i sample-maven -s https://fortify.cyberxdemo.com:14443/ -a koeIFKXW:ZhuYl0xSrh4vIfWrwSV9lk9JZV6bpnNEWp2fF1ChnLXk ./sample-application.zip
      
    #- name: Nexus IQ Policy Evaluation
      #uses: sonatype-nexus-community/iq-github-action@master
      #with:
        #serverUrl: https://fortify.cyberxdemo.com:14443/
        #username: koeIFKXW
        #password: ${{ secrets.SONATYPE_PWD }}
        #applicationId: sample-maven
        #stage: Build
        #target: ./target/
